# Generated by Django 2.0.8 on 2018-08-14 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apps',
            new_name='App',
        ),
        migrations.RenameModel(
            old_name='Guides',
            new_name='Guide',
        ),
        migrations.RenameModel(
            old_name='Links',
            new_name='Link',
        ),
        migrations.RenameModel(
            old_name='Modules',
            new_name='Module',
        ),
    ]
